//criar pedido POST http://localhost:3003/order/postorder
{
    "productId": "1a1c5631-d930-4759-82b2-eeaa61763c19",
    "variationSizeId": "<id do tamanho/estoque escolhido, obrigatório se o produto tiver variações>",
    "quantity": 1
}



### //busca endereços por usuário GET http://localhost:3003/order/getorderbyuser/:id 

### // deletar endereço DELETE http://localhost:3003/order/deleteorder/:id