//criar produto POST http://localhost:3003/product/postproduct
{
    "name": "Bolsa de mensageiro decorativa de bolso frontal ", 
    "description": "Cor: Amarelo; Tipo das alças: Ajustável; Estampa: Desenho Animado; Estilo: Universitário; Tamanho da bolsa: Pequeno; Tipo: Bolsa quadrada; Composição: 100% Algodão; Material: Tecido" , 
    "price": "39,95" , 
    "created": "2022-12-09",
    "category" : "BA"
}


### //imagem POST http://localhost:3003/product/postimage/:id

{
    "photos": "https://img.ltwebstatic.com/images3_pi/2021/12/10/1639122398d26d50b063582096773d92621b343ebc.webp"
}

### //tamanho POST http://localhost:3003/product/postsize/:id

{"sizes": "TAMANHO ÚNICO"}


### //busca produtos GET http://localhost:3003/product/products 

### //busca produto por categoria GET http://localhost:3003/product//getproducts/:category

### //busca produtos por id GET http://localhost:3003/product/product/:id

### //busca imagens por id do produto  GET http://localhost:3003/product/getAllImagesByProduct/:id

### //busca sizes por id do produto GET http://localhost:3003/product/getAllSizesByProduct/:id


### // editar produto

PUT http://localhost:3003/product/updateproduct Authorization: token 

{
        "id": "1a1c5631-d930-4759-82b2-eeaa61763c19",
         "name": "Bolsa de mensageiro decorativa",
        "description": "Cor: Amarelo; Tipo das alças: Ajustável; Estampa: Desenho Animado; Estilo: Universitário; Tamanho da bolsa: Pequeno; Tipo: Bolsa quadrada; Composição: 100% Algodão; Material: Tecido",
        "price": "39,95",
        "category": "BA"
    }

### // deletar produto DELETE http://localhost:3003/product/deleteproduct/:id 
### // deletar imagem DELETE http://localhost:3003/product/deleteimage/:id
### // deletar tamanho DELETE http://localhost:3003/product/deletesize/:id